config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :listings, only: [:show] do
    resources :listing_images, only: [:index]
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :listing_images
  has_many :reviews
  has_many :listing_sub_categories
end

app/models/listing_image.rb
class ListingImage < ApplicationRecord
  belongs_to :listing
end

app/models/listing_sub_category.rb
class ListingSubCategory < ApplicationRecord
  belongs_to :listing
  belongs_to :sub_category
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :listing
  belongs_to :user
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.fetch(:booking, {})
    end
end

app/controllers/listing_images_controller.rb
class ListingImagesController < ApplicationController

  def index
  @test = 'hitesh'
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def show
    # joining two or more tables using includes
    # @list_var has listing data and listing image data and review data for listing id = 1
    # @list_var = Listing.includes(:listing_images, :reviews, :listing_sub_categories)
    #                    .where(listings: { id: params[:id] })

    @list_var = Listing.includes(:listing_images, :listing_sub_categories,
                                 :reviews => :user)
      .where(listings: { id: params[:id] })

    @secondary_images = @list_var[0].listing_images
    @reviews = @list_var[0].reviews
    @sub_categories_array = @list_var[0].listing_sub_categories

    # getting sub-categories ids 1,5,7
    sub_cat_id = @sub_categories_array.map { |subcategory| subcategory.id }
    # select * from sub_category where id in [1,5,7];
    @sub_categories = SubCategory.where("id in (?)", sub_cat_id)

    # x = [1,2,3]
    # squarex = x.map{ |y| y*y }
    # puts squarex.inspect
  end

  def index
    @anothervar = "this is test"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @listings = Listing.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
</div>

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", booking %>
    </p>
  <% end %>
</div>

<%= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

<div>
  <%= link_to "Edit this booking", edit_booking_path(@booking) %> |
  <%= link_to "Back to bookings", bookings_path %>

  <%= button_to "Destroy this booking", @booking, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "shared/navbar" %>
    <title>Abnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/listing_images/index.html.erb
<p><%= @test %></p>

app/views/listings/_reviews.html.erb
<div class="container">
  <%# <div id="reviews" class="review-section">
    <div class="d-flex align-items-center justify-content-between mb-4">
      <h4 class="m-0">37 Reviews</h4>
      <select class="custom-select custom-select-sm border-0 shadow-sm ml-2 select2-hidden-accessible" data-select2-id="1" tabindex="-1" aria-hidden="true">
        <option data-select2-id="3">Most Relevant</option>
        <option>Most Recent</option>
      </select>
      <span class="select2 select2-container select2-container--default" dir="ltr" data-select2-id="2" style="width: 188px;">
        <span class="selection">
          <span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-qd66-container">
            <span class="select2-selection__rendered" id="select2-qd66-container" role="textbox" aria-readonly="true" title="Most Relevant">Most Relevant</span>
            <span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span>
          </span>
        </span>
        <span class="dropdown-wrapper" aria-hidden="true"></span>
      </span>
    </div>
    <div class="row">
      <div class="col-md-6">
        <table class="stars-counters">
          <tbody>
            <tr class="">
              <td>
                <span>
                  <button class="fit-button fit-button-color-blue fit-button-fill-ghost fit-button-size-medium stars-filter">5 Stars</button>
                </span>
              </td>
              <td class="progress-bar-container">
                <div class="fit-progressbar fit-progressbar-bar star-progress-bar">
                  <div class="fit-progressbar-background">
                    <span class="progress-fill" style="width: 97.2973%;"></span>
                  </div>
                </div>
              </td>
              <td class="star-num">(36)</td>
            </tr>
            <tr class="">
              <td>
                <span>
                  <button class="fit-button fit-button-color-blue fit-button-fill-ghost fit-button-size-medium stars-filter">5 Stars</button>
                </span>
              </td>
              <td class="progress-bar-container">
                <div class="fit-progressbar fit-progressbar-bar star-progress-bar">
                  <div class="fit-progressbar-background">
                    <span class="progress-fill" style="width: 2.2973%;"></span>
                  </div>
                </div>
              </td>
              <td class="star-num">(2)</td>
            </tr>
            <tr class="">
              <td>
                <span>
                  <button class="fit-button fit-button-color-blue fit-button-fill-ghost fit-button-size-medium stars-filter">5 Stars</button>
                </span>
              </td>
              <td class="progress-bar-container">
                <div class="fit-progressbar fit-progressbar-bar star-progress-bar">
                  <div class="fit-progressbar-background">
                    <span class="progress-fill" style="width: 0;"></span>
                  </div>
                </div>
              </td>
              <td class="star-num">(0)</td>
            </tr>
            <tr class="">
              <td>
                <span>
                  <button class="fit-button fit-button-color-blue fit-button-fill-ghost fit-button-size-medium stars-filter">5 Stars</button>
                </span>
              </td>
              <td class="progress-bar-container">
                <div class="fit-progressbar fit-progressbar-bar star-progress-bar">
                  <div class="fit-progressbar-background">
                    <span class="progress-fill" style="width: 0;"></span>
                  </div>
                </div>
              </td>
              <td class="star-num">(0)</td>
            </tr>
            <tr class="">
              <td>
                <span>
                  <button class="fit-button fit-button-color-blue fit-button-fill-ghost fit-button-size-medium stars-filter">5 Stars</button>
                </span>
              </td>
              <td class="progress-bar-container">
                <div class="fit-progressbar fit-progressbar-bar star-progress-bar">
                  <div class="fit-progressbar-background">
                    <span class="progress-fill" style="width: 0;"></span>
                  </div>
                </div>
              </td>
              <td class="star-num">(0)</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-md-6">
        <div class="ranking">
          <h6 class="text-display-7">Rating Breakdown</h6>
          <ul>
            <li>
              Seller communication level<span>5<span class="review-star rate-10 show-one"></span></span>
            </li>
            <li>
              Recommend to a friend<span>5<span class="review-star rate-10 show-one"></span></span>
            </li>
            <li>
              Service as described<span>4.9<span class="review-star rate-10 show-one"></span></span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div> %>
  <div class="container">
    <div class="review-list">
      <% @reviews.each do |review| %>
        <ul>
          <li>
            <div class="d-flex">
              <div class="left">
                <span>
                  <img src="https://bootdey.com/img/Content/avatar/avatar1.png" class="profile-pict-img img-fluid" alt="" />
                </span>
              </div>
              <div class="right">
                <h4>
                  <%= review.user.email%>
                  <span class="gig-rating text-body-2">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1792 1792" width="15" height="15">
                      <path
                                        fill="currentColor"
                                        d="M1728 647q0 22-26 48l-363 354 86 500q1 7 1 20 0 21-10.5 35.5t-30.5 14.5q-19 0-40-12l-449-236-449 236q-22 12-40 12-21 0-31.5-14.5t-10.5-35.5q0-6 2-20l86-500-364-354q-25-27-25-48 0-37 56-46l502-73 225-455q19-41 49-41t49 41l225 455 502 73q56 9 56 46z"
                                    ></path>
                    </svg>
                    <%= review.rating%>
                  </span>
                </h4>
                <div class="country d-flex align-items-center">
                  <span>
                    <img class="country-flag img-fluid" src="https://bootdey.com/img/Content/avatar/avatar6.png" />
                  </span>
                  <div class="country-name font-accent"><%= review.title%></div>
                </div>
                <div class="review-description">
                  <p>
                    <%= review.body%>
                  </p>
                </div>
                <div class="helpful-thumbs">
                  <div class="helpful-thumb text-body-2">
                    <span class="fit-icon thumbs-icon">
                      <svg width="14" height="14" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg">
                        <path
                                            d="M13.5804 7.81165C13.8519 7.45962 14 7 14 6.43858C14 5.40843 13.123 4.45422 12.0114 4.45422H10.0932C10.3316 3.97931 10.6591 3.39024 10.6591 2.54516C10.6591 0.948063 10.022 0 8.39207 0C7.57189 0 7.26753 1.03682 7.11159 1.83827C7.01843 2.31708 6.93041 2.76938 6.65973 3.04005C6.01524 3.68457 5.03125 5.25 4.44013 5.56787C4.38028 5.59308 4.3038 5.61293 4.22051 5.62866C4.06265 5.39995 3.79889 5.25 3.5 5.25H0.875C0.391754 5.25 0 5.64175 0 6.125V13.125C0 13.6082 0.391754 14 0.875 14H3.5C3.98325 14 4.375 13.6082 4.375 13.125V12.886C5.26354 12.886 7.12816 14.0002 9.22728 13.9996C9.37781 13.9997 10.2568 14.0004 10.3487 13.9996C11.9697 14 12.8713 13.0183 12.8188 11.5443C13.2325 11.0596 13.4351 10.3593 13.3172 9.70944C13.6578 9.17552 13.7308 8.42237 13.5804 7.81165ZM0.875 13.125V6.125H3.5V13.125H0.875ZM12.4692 7.5565C12.9062 7.875 12.9062 9.1875 12.3159 9.48875C12.6856 10.1111 12.3529 10.9439 11.9053 11.1839C12.1321 12.6206 11.3869 13.1146 10.3409 13.1246C10.2504 13.1255 9.32247 13.1246 9.22731 13.1246C7.23316 13.1246 5.54296 12.011 4.37503 12.011V6.44287C5.40611 6.44287 6.35212 4.58516 7.27847 3.65879C8.11368 2.82357 7.83527 1.43153 8.3921 0.874727C9.78414 0.874727 9.78414 1.84589 9.78414 2.54518C9.78414 3.69879 8.94893 4.21561 8.94893 5.32924H12.0114C12.6329 5.32924 13.1223 5.88607 13.125 6.44287C13.1277 6.99967 12.9062 7.4375 12.4692 7.5565ZM2.84375 11.8125C2.84375 12.1749 2.54994 12.4688 2.1875 12.4688C1.82506 12.4688 1.53125 12.1749 1.53125 11.8125C1.53125 11.4501 1.82506 11.1562 2.1875 11.1562C2.54994 11.1562 2.84375 11.4501 2.84375 11.8125Z"
                                        ></path>
                      </svg>
                    </span>
                    <span class="thumb-title">Helpful</span>
                  </div>
                  <div class="helpful-thumb text-body-2 ml-3">
                    <span class="fit-icon thumbs-icon">
                      <svg width="14" height="14" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg">
                        <path
                                            d="M0.419563 6.18835C0.148122 6.54038 6.11959e-07 7 5.62878e-07 7.56142C2.81294e-05 8.59157 0.876996 9.54578 1.98863 9.54578L3.90679 9.54578C3.66836 10.0207 3.34091 10.6098 3.34091 11.4548C3.34089 13.0519 3.97802 14 5.60793 14C6.42811 14 6.73247 12.9632 6.88841 12.1617C6.98157 11.6829 7.06959 11.2306 7.34027 10.9599C7.98476 10.3154 8.96875 8.75 9.55987 8.43213C9.61972 8.40692 9.6962 8.38707 9.77949 8.37134C9.93735 8.60005 10.2011 8.75 10.5 8.75L13.125 8.75C13.6082 8.75 14 8.35825 14 7.875L14 0.875C14 0.391754 13.6082 -3.42482e-08 13.125 -7.64949e-08L10.5 -3.0598e-07C10.0168 -3.48226e-07 9.625 0.391754 9.625 0.875L9.625 1.11398C8.73647 1.11398 6.87184 -0.000191358 4.77272 0.00038257C4.62219 0.000300541 3.74322 -0.000438633 3.65127 0.000382472C2.03027 -1.04643e-06 1.12867 0.981667 1.18117 2.45566C0.76754 2.94038 0.564868 3.64065 0.682829 4.29056C0.342234 4.82448 0.269227 5.57763 0.419563 6.18835ZM13.125 0.875L13.125 7.875L10.5 7.875L10.5 0.875L13.125 0.875ZM1.53079 6.4435C1.09375 6.125 1.09375 4.8125 1.6841 4.51125C1.31436 3.88891 1.64713 3.05613 2.09467 2.81605C1.86791 1.37941 2.61313 0.885417 3.65906 0.875355C3.74962 0.874535 4.67753 0.875355 4.77269 0.875355C6.76684 0.875355 8.45704 1.98898 9.62497 1.98898L9.62497 7.55713C8.5939 7.55713 7.64788 9.41484 6.72153 10.3412C5.88632 11.1764 6.16473 12.5685 5.6079 13.1253C4.21586 13.1253 4.21586 12.1541 4.21586 11.4548C4.21586 10.3012 5.05107 9.78439 5.05107 8.67076L1.9886 8.67076C1.36708 8.67076 0.877707 8.11393 0.874973 7.55713C0.872266 7.00033 1.09375 6.5625 1.53079 6.4435ZM11.1563 2.1875C11.1563 1.82506 11.4501 1.53125 11.8125 1.53125C12.1749 1.53125 12.4688 1.82506 12.4688 2.1875C12.4688 2.54994 12.1749 2.84375 11.8125 2.84375C11.4501 2.84375 11.1563 2.54994 11.1563 2.1875Z"
                                        ></path>
                      </svg>
                    </span>
                    <span class="thumb-title">Not Helpful</span>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>
      <% end %>
    </div>
  </div>

app/views/listings/index.html.erb
<p><%= @anothervar %></p>

app/views/listings/show.html.erb
<div class="container">
  <div class= "row">
    <h2><%= @list_var[0].headline%></h2>
    <h5><%= @list_var[0].city%> <%= @list_var[0].state%> <%= @list_var[0].country%></h5>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <img   width="600" height="600"
      src= <%= @list_var[0].primary_image_url %>
      alt="Boat on Calm Water"
    /></div>
    <div class="col-sm-6">
      <div class="row">
        <% @secondary_images.each do |img| %>
          <div class='col-6 col-sm-6'>
            <img  width="297" height="297" class = "mb-2"
                src= <%= img.listing_image_secondary_url %> />
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class = "row">
    <h4>
      <%= @list_var[0].name%>
    </h4>
    <p><%= @list_var[0].description%> </p>
  </div>
  <div class = "row">
    <h2>Reviews</h2>
    <%= render "reviews", object: @reviews %>
  </div>
  <div class = "row">
    <h2>What this place offers</h2>
    <% @sub_categories.each do |subcate| %>
      <div class='col-6 col-sm-6'>
        <p><%= subcate.sub_category_name%></p>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class = "container">
  <div class="row row-cols-4">
    <% @listings.each do |listing| %>
      <div class="col">
        <div class="card">
          <div class="card-body">
            <%=link_to listing_path(listing) do%>
              <img  width="300" height="300"
                        src= <%= listing.primary_image_url %>
                        alt="Boat on Calm Water"/>
              <h5 class="card-title"><%= listing.city %></h5>
              <h5 class="card-title"><%=listing.country%></h5>
              <h6 class="card-title"><%=listing.price%> $</h6>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">

    </form>
  </div>
</nav>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>